import { test, expect } from "@playwright/test";
import { randomUUID, randomBytes, scryptSync } from "node:crypto";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const listing = { genderId: "gender-unisex", seasonId: "season-summer", category: "ao", materialId: "material-cotton", sizeId: "size-m", brandId: "brand-no-brand", salePrice: 120000 };
test.afterAll(async () => { await prisma.$disconnect(); });
test.describe("admin review in disposable database", () => {
  test.skip(process.env.RUN_ADMIN_DB_E2E !== "1", "Only run against an isolated disposable DB");
  test("login, session protection, review audit, and concurrent conflict", async ({ page, baseURL }) => {
    const suffix = randomUUID();
    const email = `admin-${suffix}@example.test`;
    const password = `FixtureOnly-${randomUUID()}`;
    const salt = randomBytes(16);
    const hash = scryptSync(password, salt, 64, { N: 16384, r: 8, p: 1, maxmem: 64 * 1024 * 1024 });
    const admin = await prisma.adminUser.create({ data: { email, active: true, passwordHash: `scrypt$16384$8$1$${salt.toString("base64url")}$${hash.toString("base64url")}` } });
    const consignor = await prisma.consignor.create({ data: { name: `Fake-${suffix}`, phoneNormalized: "0000000000" } });
    const receipt = await prisma.consignment.create({ data: { publicCode: `FAKE-${suffix}`, consignorId: consignor.id, intakeType: "CONSIGN" } });
    const pending = await prisma.item.create({ data: { consignmentId: receipt.id, slug: `fake-${suffix}`, name: "Fake test item", category: "ao", condition: "Fake", description: "Disposable test", status: "PENDING" } });
    const rejectedItem = await prisma.item.create({ data: { consignmentId: receipt.id, slug: `fake-reject-${suffix}`, name: "Fake reject test item", category: "ao", condition: "Fake", description: "Disposable test", status: "PENDING" } });
    const request = page.request;
    const origin = `http://localhost:${new URL(baseURL!).port}`;
    const headers = { Origin: origin };
    await page.goto(`/admin/items/${pending.id}`);
    await expect(page).toHaveURL(/\/admin\/login$/);
    const bad = await request.post(`${origin}/api/admin/session`, { headers, data: { email, password: "not-correct" } });
    expect(bad.status()).toBe(401);
    const login = await request.post(`${origin}/api/admin/session`, { headers, data: { email, password } });
    expect(login.status(), await login.text()).toBe(200);
    await page.goto(`${origin}/admin/items/${pending.id}`);
    await expect(page.getByText("0000000000")).toBeVisible();
    await page.goto(`${origin}/admin/items?status=pending`);
    await expect(page.locator(`a[href="/admin/items/${pending.id}"]`)).toBeVisible();
    const url = `${origin}/api/admin/items/${pending.id}`;
    const mutationHeaders = { Origin: origin, "Content-Type": "application/json" };

    const noPrice = await request.patch(url, { headers: mutationHeaders, data: { action: "approve", expectedStatus: "PENDING" } });
    expect(noPrice.status()).toBe(422);
    const invalidReason = await request.patch(`${origin}/api/admin/items/${rejectedItem.id}`, { headers: mutationHeaders, data: { action: "reject", expectedStatus: "PENDING", reason: "x".repeat(1001) } });
    expect(invalidReason.status()).toBe(422);
    const csrf = await request.patch(url, { headers: { Origin: "https://malicious.invalid" }, data: { action: "approve", expectedStatus: "PENDING", salePrice: 120000 } });
    expect(csrf.status()).toBe(403);
    const negotiating = await request.patch(url, { headers: mutationHeaders, data: { action: "negotiate", expectedStatus: "PENDING" } });
    expect(negotiating.status()).toBe(200);
    const received = await request.patch(url, { headers: mutationHeaders, data: { action: "receive", expectedStatus: "NEGOTIATING" } });
    expect(received.status()).toBe(200);
    const approved = await request.patch(url, { headers: mutationHeaders, data: { action: "approve", expectedStatus: "RECEIVED", ...listing } });
    expect(approved.status(), await approved.text()).toBe(200);
    const conflict = await request.patch(url, { headers: mutationHeaders, data: { action: "approve", expectedStatus: "RECEIVED", ...listing } });
    expect(conflict.status()).toBe(409);
    const item = await prisma.item.findUnique({ where: { id: pending.id }, include: { statusEvents: true } });
    expect(item?.salePrice?.toNumber()).toBe(120000);
    expect(item?.status).toBe("APPROVED");
    expect(item?.reviewedById).toBe(admin.id);
    expect(item?.reviewedAt).not.toBeNull();
    expect(item?.publishedAt).not.toBeNull();
    expect(item?.statusEvents).toHaveLength(3);
    expect(item?.statusEvents[0].actorAdminId).toBe(admin.id);
    const rejected = await request.patch(`${origin}/api/admin/items/${rejectedItem.id}`, { headers: mutationHeaders, data: { action: "reject", expectedStatus: "PENDING", reason: "Không đạt" } });
    expect(rejected.status()).toBe(200);
    expect((await prisma.item.findUnique({ where: { id: rejectedItem.id }, include: { statusEvents: true } }))?.statusEvents).toHaveLength(1);
    const sold = await request.patch(url, { headers: mutationHeaders, data: { action: "sold", expectedStatus: "APPROVED" } });
    expect(sold.status()).toBe(200);
    const settled = await request.patch(url, { headers: mutationHeaders, data: { action: "settle", expectedStatus: "SOLD" } });
    expect(settled.status()).toBe(200);
    const finalItem = await prisma.item.findUnique({ where: { id: pending.id }, include: { statusEvents: true } });
    expect(finalItem?.status).toBe("SETTLED");
    expect(finalItem?.statusEvents).toHaveLength(5);
    const logout = await request.delete(`${origin}/api/admin/session`, { headers });
    expect(logout.status()).toBe(200);
    expect((await request.patch(url, { headers: mutationHeaders, data: { action: "hidden", expectedStatus: "APPROVED" } })).status()).toBe(401);
  });
});
